### ISSUE TITLE
Code blocks (three backticks) all go to single line

### ISSUE THREAD

**Issue by Mikaela** [victorstanciu/Wikitten#48]
For example:

<pre>

```
ufw allow 113
ufw allow 631
ufw allow 100XX
ufw limit 22
ufw enable
```

</pre>

from https://wiki.mikaela.info/Me%20%28Mikaela%29/New%C2%A0systems.md becomes 

`ufw allow 113 ufw allow 631 ufw allow 100XX ufw limit 22 ufw enable`

while it should become

```
ufw allow 113
ufw allow 631
ufw allow 100XX
ufw limit 22
ufw enable
```

this can be also reproduced with most of other markdown files on wiki.mikaela.info.

**Comment by Kovah** [comment]
Should be posted to https://github.com/michelf/php-markdown as this is the library used by Wikitten.

**Comment by Mikaela** [comment]
Moved to https://github.com/michelf/php-markdown/issues/197
