### ISSUE TITLE
blank page

### ISSUE THREAD

**Issue by wxl** [victorstanciu/Wikitten#50]
so i loaded everything up and all was well. so i removed all the files in `library` and changed `index.md` to my liking and reloaded and i get a blank page.

**Comment by Kovah** [comment]
Had the same problem and got the following error:
```
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'There was an error parsing the JSON Front Matter for this page: Incorrect JSON syntax (missing comma, or double-quotes?)
```
In my case I used the usual `---` to create a line but it's converted to JSON if you enable `USE_PAGE_METADATA` in the `config.php`
Use `* * *` instead.
