### ISSUE TITLE
Default file extension

### ISSUE THREAD

**Issue by stevenandres** [victorstanciu/Wikitten#65]
Would be nice to have cleaner URLs such as 

http://server/support    (really support.md on disk)
http://server/contact    (really contact.md on disk)
http://server/todo       (really todo.md on disk)

and when Wikitten notices there's no extension, it implies ".md" at the end. This allows a "pretty" URL and on disk, still stored as MarkDown. This would require tweaks of the tree.php as well. I made this change in index.php, just after `$request_uri = parse_url($_SERVER['REQUEST_URI']);`

```
if( strlen(pathinfo($request_uri['path'], PATHINFO_EXTENSION)) === 0) {
    $request_uri['path'] .= ".md";
}
```

but I think there's more work to be done

**Comment by tamano** [comment]
Hi, 
I have implemented this on a forked project below. 

https://github.com/nicosomb/Wikitten/pull/8

Hope it will help.

**Comment by stevenandres** [comment]
THANK YOU!!!!!!

**Comment by tamano** [comment]
We can't :(
Maybe @victorstanciu will!

**Comment by georgesuba** [comment]
@stevenandres you can close your own issue here in reply.. press close on comment instead of comment

**Comment by stevenandres** [comment]
closing
