### ISSUE TITLE
HTTP 200 when page doesn't exist

### ISSUE THREAD

**Issue by sebw** [victorstanciu/Wikitten#71]
index2.md doesn't exist and thus goes to the uhoh.php page:

    curl -I http://wikitten.vizuina.com/index2.md
    HTTP/1.1 200 OK
    Date: Tue, 19 Jan 2016 15:32:37 GMT
    Server: Apache/2.2.22 (Ubuntu)
    X-Powered-By: PHP/5.4.45-3+deb.sury.org~precise+1
    Vary: Accept-Encoding
    Content-Type: text/html

By inserting the following in uhoh.php, it returns a 404 and prevents dead links from being indexed:

    <?php header("HTTP/1.0 404 Not Found"); ?>

**Comment by victorstanciu** [comment]
Fixed in #fc8c5d6b5e4e7be63ec18c7f47e524e2782cdbb9
