### ISSUE TITLE
Why is there an inconsistency between the live version and the GitHub version?

### ISSUE THREAD

**Issue by praveenscience** [victorstanciu/Wikitten#77]
I could see a few things:

1. Bootstrap version.
2. Plugin CSS are different.

For Eg., this affect it so much. When I **install this from GitHub**, I get:

![image](https://cloud.githubusercontent.com/assets/1830380/13190852/bfc2d8a2-d757-11e5-9879-06fc8f75d703.png)

But the live version has:

![image](https://cloud.githubusercontent.com/assets/1830380/13190872/d4f91420-d757-11e5-9d6c-f5c8e31921fd.png)

See the **Code Formats**, which I am more interested in. The line numbers and the formatting is not so good.

**Comment by praveenscience** [comment]
The PR #76 automatically fixes this issue.

**Comment by victorstanciu** [comment]
I simply forgot to update the live demo, thanks!

**Comment by praveenscience** [comment]
Yay! Wow.
