### ISSUE TITLE
Nginx?

### ISSUE THREAD

**Issue by Furgas** [victorstanciu/Wikitten#81]
What would be nginx equivalent of .htaccess rewrite rules for the wiki to run properly?

**Comment by azlux** [comment]
@Furgas : https://github.com/victorstanciu/Wikitten/wiki/nginx-configuration
Here there are a configuration.
But it's only if you're in the root. it's not my case, and i don't found the good conf when i'm into the /wiki folder

**Comment by Furgas** [comment]
Thanks. It works.
